### ISSUE TITLE
OOM (Out Of Memory) Issue during inference

### ISSUE THREAD

**Issue by Dev-HJYoo** [THUDM/CogVideo#803]
### System Info / 系統信息

Hardware
- v100 x 4
- ubuntu 22.04
- python 3.10
- CUDA 11.8

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

bash

`PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python cli_demo.py --prompt "A girl riding a bike." --model_path ../model/CogVideoX1.5-5B --generate_type "t2v"`

result

```
INFO:root:Using default resolution (768, 1360) for cogvideox1.5-5b
Loading pipeline components...:  20%|████████████                                                | 1/5 [00:00<00:00,  5.39it/s]`torch_dtype` is deprecated! Use `dtype` instead!
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.90it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 25.88it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.74it/s]
  0%|                                                                                                   | 0/50 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/cogvideo/inference/cli_demo.py", line 254, in <module>
    generate_video(
  File "/cogvideo/inference/cli_demo.py", line 171, in generate_video
    video_generate = pipe(
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 722, in __call__
    noise_pred = self.transformer(
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/accelerate/hooks.py", line 175, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 430, in forward
    hidden_states, encoder_hidden_states = block(
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 135, in forward
    attn_hidden_states, attn_encoder_hidden_states = self.attn1(
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 605, in forward
    return self.processor(
  File "/root/miniconda3/envs/cogvideo/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 2327, in __call__
    hidden_states = F.scaled_dot_product_attention(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 727.61 GiB. GPU 0 has a total capacity of 31.74 GiB of which 22.37 GiB is free. Process 29827 has 9.37 GiB memory in use. Of the allocated memory 8.33 GiB is allocated by PyTorch, and 55.33 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[W1218 05:20:19.536079467 AllocatorConfig.cpp:28] Warning: PYTORCH_CUDA_ALLOC_CONF is deprecated, use PYTORCH_ALLOC_CONF instead (function operator())

``` 

### Expected behavior / 期待表现

When reviewing other related issues, I noticed that the reported VRAM usage typically ranges between 20–40 GB.
However, in my case, the process attempts to allocate more than 700 GB of VRAM, which seems abnormal.

This makes me suspect that there may be a misconfiguration or an unexpected issue in my setup.

I would greatly appreciate any guidance or suggestions on how to resolve this problem.
Thank you in advance for your help.

Additionally, I tested the following command:

`python cli_demo.py \
  --prompt "A girl riding a bike." \
  --model_path THUDM/CogVideoX1.5-5b \
  --generate_type "t2v"`

However, the same issue occurs, with the process still attempting to allocate an abnormally large amount of VRAM.

**Comment by Dev-HJYoo** [comment]
Issue resolved.

It seems that V100 GPUs do not support BF16.
Because of this, inference was causing unexpected problems.

After switching to:

--dtype float16


the issue was resolved.

If anyone else encounters problems during inference on a V100, I recommend changing the dtype to float16 as well.
